// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfjpxbilihusruuvfgdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmanB4YmlsaWh1c3J1dXZmZ2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NDc5NjAsImV4cCI6MjA1NzEyMzk2MH0.0RFYvMUoGs9e6PvsDu9g6I-tBeFIgQDDHmBnhriYotc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);